Caleb hill seth updates
hyperledger-archives/sawtooth-docs-archive pull request #144
Opened 2022-01-14 20:51 UTC by Caleb-Hill

Updates to the seth directory markdown files.

2022-01-20 19:23 UTC, agunde406 requested changes

2022-01-20 19:23 UTC, agunde406 commented on docs/seth/0.2/contracts.md
> +## Compiling Contracts {#compiling-contracts}
The getting started link on line 67 should be fixed

2022-01-20 19:23 UTC, agunde406 commented on docs/seth/0.2/permissions.md
> +
the link to the introduction below should be updated

2022-01-20 19:23 UTC, agunde406 commented on docs/seth/0.2/dapps.md
> +(seth-rpc)[./cli_reference.html#seth-rpc-reference-label]
Formatting switch here ()[] instead of []()

2022-01-20 19:23 UTC, agunde406 commented on docs/seth/0.2/seth_transaction_family_spec.md
> +## Execution {#execution}
There is some formatting issues with the lists in this section.

2022-02-03 21:26 UTC, vaporos approved these changes

2022-07-19 15:53 UTC, agunde406 commented
This documentation will not be ported to the website.

2022-07-19 15:53 UTC, closed without merging