Update 1.1 app dev guide - address and namespace design
hyperledger-archives/sawtooth-docs-archive pull request #146
Opened 2022-01-14 22:18 UTC by isabeltomb

2022-01-20 19:41 UTC, agunde406 requested changes
The image should be moved to "images/1.1" instead of "docs/1.1/images

2022-01-31 18:59 UTC, peterschwarz approved these changes

2022-01-31 19:09 UTC, vaporos approved these changes

2022-01-31 19:09 UTC, agunde406 approved these changes

2022-01-31 19:09 UTC, merged