Add Bloxiom to Users List
hyperledger-archives/sawtooth-docs-archive pull request #45
Opened 2019-04-22 15:54 UTC by mmsidani

Appended information about Bloxiom's use of Sawtooth to the end of generator/source/_data/users.yml .

Signed-off-by: majed <mmsidani@gmail.com>

2019-04-22 15:56 UTC, peterschwarz commented
Your commit message looks poorly formatted (though I see the idea you are going for).  You should do a `git commit --amend` and correct the use of `\n` in there to actual new lines.

2019-04-22 16:22 UTC, danintel requested changes
As Peter mentioned, the commit message is wrong.

You do not need to close and open PRs to make changes.  Just force push (`push -f`) changes to your repository on github.com

2019-04-22 16:38 UTC, mmsidani commented
Just amended and force pushed.

From: Dan Anderson
Sent: Monday, April 22, 2019 12:22 PM
To: hyperledger/sawtooth-website
Cc: mmsidani; Author
Subject: Re: [hyperledger/sawtooth-website] Add Bloxiom to Users List (#45)

@danintel requested changes on this pull request.
As Peter mentioned, the commit message is wrong.
You do not need to close and open PRs to make changes. Just force push (push -f) changes to your repository on github.com
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-04-22 21:06 UTC, danintel approved these changes

2019-04-23 21:09 UTC, peterschwarz approved these changes

2019-04-23 21:10 UTC, annechenette approved these changes

2019-04-23 22:33 UTC, merged