Bumper release notes
hyperledger-archives/sawtooth-docs-archive pull request #8
Opened 2018-11-05 21:01 UTC by aludvik

2018-11-05 21:03 UTC, chenette commented on generator/source/index.md
> +The latest release of Hyperledger Sawtooth is 1.1, codename Bumper.
Is it bumper or Bumper?

2018-11-06 17:06 UTC, vaporos approved these changes

2018-11-06 17:09 UTC, dcmiddle requested changes

2018-11-06 17:09 UTC, dcmiddle commented on generator/source/release/bumper/notes.md
> +  RFC](https://github.com/hyperledger/sawtooth-rfcs/pull/8) for more details:
:s/:/.

2018-11-07 16:53 UTC, aludvik commented
@dcmiddle fixed punctuation typo

2018-11-07 18:02 UTC, dcmiddle approved these changes

2018-11-09 22:00 UTC, aludvik commented
Rebased on master to pick up Jenkinsfile

2018-11-13 01:58 UTC, aludvik commented
Wait until release is live to merge

2018-12-04 17:31 UTC, annechenette reviewed
The documentation section appears incomplete - it appears that the only doc changes were to add a Rust SDK and a glossary.  I can provide an additional commit with the formatting changes.

2018-12-04 23:57 UTC, aludvik commented
@chenette I think it looks cleaner with the sub-headings.

![before](https://user-images.githubusercontent.com/24274338/49480878-342d0980-f7dd-11e8-951b-817a5abed672.png)

![after](https://user-images.githubusercontent.com/24274338/49480887-398a5400-f7dd-11e8-953a-dab2781ecb3d.png)

2018-12-05 00:09 UTC, chenette commented
I suspect that's because the sub-bullets (dashes) aren't rendering correctly in this view.  I assume that the indenting would be correct on the website, because my online markdown viewers assure me that the sub-bullet indents are correct. Also, it's identical to the format used in the Consensus section.

2018-12-05 00:18 UTC, chenette commented
I stand corrected.  I need more spaces for my indented lists.  I shall push a fix for the Documentation section, then follow with a fix for the Consensus section.

> To nest one list within another, indent each item in the sublist by four spaces.

2018-12-05 00:52 UTC, chenette commented
@aludvik - I wasn't able to get nested (indented) lists working in the "build artifacts". I don't know if this is just an issue with the build environment, but I don't want to risk introducing these format errors in the website.  So I pushed a fixup commit that makes the subheading approach consistent  by changing the first two bullets to subheads. I hope this is an acceptable compromise.

2018-12-05 16:13 UTC, vaporos approved these changes

2018-12-06 16:45 UTC, closed without merging