Refresh branch: faq folder
hyperledger-archives/sawtooth-docs-archive pull request #84
Opened 2021-01-19 15:05 UTC by kentydotcom

Converted all faq rst files into md (English).
Checked via local docker Jekyll renderer.

2021-01-21 22:14 UTC, vaporos requested changes

2021-01-21 22:14 UTC, vaporos commented on faq/client.md
> +<!--
Copyright should come after the first header and look like line one here (with the appropriate copyright):

https://raw.githubusercontent.com/Cargill/splinter-docs/master/docs/0.4/index.md

(same applies to all other headers that look like this)

2021-01-21 22:14 UTC, vaporos commented on faq/client.md
> +---
These division lines should be omitted in the markdown. (same for other instances)

2021-01-21 22:14 UTC, vaporos commented on faq/client.md
> +<!--::: {.mininav}
Remove the commented-out pieces like this that don't get rendered.

2021-01-21 22:14 UTC, vaporos commented on faq/faq.md
> +-   [Hyperledger Sawtooth in General](sawtooth)
These links are broken. You can test the site by running "just run" (after installing 'just') and pointing the browser to http://localhost:4000/.

The correct way to write these particular lines is:

```
 -   [Hyperledger Sawtooth in General]({% link faq/sawtooth.md %})
```

2021-01-21 22:14 UTC, vaporos commented on faq/faq.md
> +© Copyright 2018, Intel Corporation.
Remove all copyrights at the end of the files (this should now be in the comment on the top of the files).

2021-01-21 22:22 UTC, vaporos commented
Please augment the commit messages following these suggestions as a guide - https://chris.beams.io/posts/git-commit/

2021-01-21 22:27 UTC, vaporos commented
Please move the internationalization to a separate PR. For reference, here is a possible plugin we can use to help with this piece in jekyll - https://github.com/kurtsson/jekyll-multiple-languages-plugin.

2021-02-18 10:43 UTC, arsulegai commented
@rbuysse @rberg2 The PR build fails because @kentydotcom is not part of approved list.

2021-02-18 14:40 UTC, rbuysse commented
> @rbuysse @rberg2 The PR build fails because @kentydotcom is not part of approved list.

👍 Kenty's been added to the authorized builders list.

2021-03-17 18:26 UTC, vaporos approved these changes, later dismissed

2021-03-17 18:48 UTC, vaporos commented
That should have read "There is a comment".

2022-07-19 16:04 UTC, agunde406 commented
This work has been completed and merged into main.

2022-07-19 16:04 UTC, closed without merging